plugins {
    alias(libs.plugins.android.library)
}

android {
    namespace = 'com.wkq.bao.feature.res'
    compileSdk = libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk = libs.versions.minSdk.get().toInteger()
        consumerProguardFiles 'consumer-rules.pro'
    }
}
